### ISSUE TITLE
Wrong repo name?

### ISSUE THREAD

**Issue by trondtynnol** [giellalt/dict-sma-mul#1]
The repo name would lead one to think that the target language of this dictionary is Norwegian bokmål only, but it also contains Swedish translations. Should it then not be `dict-sma-mul`?

**Comment by snomos** [comment]
I agree. If no-one protests I will rename the repo.

**Comment by snomos** [comment]
Renamed.

**Comment by th0masbk** [comment]
Vi skulle nok hatt en diskusjon rundt dette før det ble gjort. Det vil føre til større og mer uoversiktlige filer, etter hvert som både de norske og svenske ordboksartiklene bygges ut til det nivået de bør være på. Det kan også gjøre terskelen høyere for å forbedre den norske artikkelen uten å bruke tid på den svenske og omvendt. Det blir også vanskelig å telle antall ordboksartikler for hvert enkelt språk, siden swe/nob er markert for hver mg, og hvert oppslagsord kan ha flere mg'er. I tillegg har vi ingen dict-swe-sma (eller dict-mul-sma).

Jeg foreslår å dele dem opp i `dict-sma-nob` og `dict-sma-swe`. Vi har en person som er interessert i å forbedre de svenske ordboksartiklene, og vi bør diskutere rekkefølgen på oppdelingen. @Trondtr hadde noen ideer til oversetting svensk -> norsk.
